import = [
"~/.config/alacritty/catppuccin-latte.toml"
#"~/.config/alacritty/catppuccin-mocha.toml"
]

[cursor]
style = "Beam"

[font.normal]
family = "MesloLGS Nerd Font Mono"

[shell]
args = ["-l", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window.padding]
x = 10
y = 10
