format = """
$os\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$fill\
$cmd_duration\
$line_break\
$character
"""

palette = 'catppuccin_latte'
#palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[character]
format = '$symbol '

[directory]
style = "fg:sky"
format = "[$path ]($style) "
truncation_length = 3
truncation_symbol = "…/"

[c]
symbol = ""
style = 'fg:sky'
format = '[$symbol]($style)[ $version ](fg:white) '

[cmd_duration]
min_time = 1000
style = 'fg:yellow'
format = '[[ $duration]($style)]($style)'

[docker_context]
symbol = " "
style = 'fg:blue'
format = '[$symbol]($style)[ $version ](fg:white) '

[fill]
symbol='━'

[git_branch]
symbol = ""
style = 'fg:red'
format = '[$symbol $branch]($style) '

[git_status]
style = 'fg:red'
format = '[$all_status$ahead_behind ]($style)'

[elixir]
symbol = ""
style = 'fg:mauve'
format = '[$symbol]($style)[ $version ](fg:white) '

[golang]
symbol = ""
style = 'fg:blue'
format = '[$symbol]($style)[ $version ](fg:white) '

[hostname]
ssh_only = false
style = 'fg:text'
format = '[$hostname]($style) '
disabled = false

[haskell]
symbol = ""
style = 'fg:mauve'
format = '[$symbol]($style)[ $version ](fg:white) '

[java]
symbol = ""
style = 'fg:peach'
format = '[$symbol]($style)[ $version ](fg:white) '

[julia]
symbol = ""
style = 'fg:lavender'
format = '[$symbol]($style)[ $version ](fg:white) '

[nodejs]
symbol = "󰎙"
style = 'fg:green'
format = '[$symbol]($style)[ $version ](fg:white) '

[os]
disabled = false
style = 'fg:text'
format = '[[$symbol]($style)]($style)'

[rust]
symbol = ""
style = 'fg:peach'
format = '[$symbol]($style)[ $version ](fg:white) '

[os.symbols]
Alpine = " "
Android = " "
Arch = "󰣇 "
Debian = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
Linux = " " # I can not be bothered to make a PR for steamos, until they add it I will just change the linux icon.
Macos = " "
Manjaro = " "
Mint = "󰣭 "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
