format = """
$os\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$fill\
$cmd_duration\
$line_break\
$character
"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[character]
format = '$symbol '

[directory]
style = "fg:directory"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[c]
symbol = ""
style = 'fg:c'
format = '[ $symbol]($style)[ $version ](fg:languages)'

[cmd_duration]
min_time = 1000
style = 'fg:duration'
format = '[[ $duration]($style)]($style)'

#[docker_context]
#symbol = " "
#format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[fill]
symbol='━'

[git_branch]
symbol = ""
style = 'fg:git'
format = '[ $symbol $branch]($style)'

[git_status]
style = 'fg:git'
format = '[ $all_status$ahead_behind ]($style)'
[elixir]
symbol = ""
style = 'fg:elixir'
format = '[$symbol]($style)[ $version ](fg:languages)'

[golang]
symbol = ""
style = 'golang'
format = '[$symbol]($style)[ $version ](fg:languages)'

[hostname]
ssh_only = false
style = 'fg:hostname'
format = '[$hostname]($style)'
disabled = false

[haskell]
symbol = ""
style = 'fg:haskell'
format = '[$symbol]($style)[ $version ](fg:languages)'

[java]
symbol = ""
style = 'fg:java'
format = '[$symbol]($style)[ $version ](fg:languages)'

[julia]
symbol = ""
style = 'fg:julia'
format = '[$symbol]($style)[ $version ](fg:languages)'

[nodejs]
symbol = ""
style = 'fg:nodejs'
format = '[$symbol]($style)[ $version ](fg:languages)'

[os]
disabled = false
style = 'fg:os'
format = '[[$symbol]($style)]($style)'

[rust]
symbol = ""
style = 'fg:rust'
format = '[$symbol]($style)[ $version ](fg:languages)'

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " " # I can not be bothered to make a PR for steamos, until they add it I will just change the linux icon.
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
