format = """
$os\
$directory\
$git_branch\
$git_status\
$c\
$elixir\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$fill\
$cmd_duration\
$line_break\
$character
"""

palette = 'personal'

[palettes.personal]
os = '#FFFFFF'
directory = '#1DA1F2'
duration = 'yellow'
git = '#F05032'
languages = '#FFFFFF'
c = '#A8B9CC'
elixir = '#4B275F'
golang = '#00ADD8'
haskell = '#5D4F85'
java = '#007396'
julia = '#9558B2'
nodejs = '#339933'
rust = '#FFFFFF'

[directory]
style = "fg:directory"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[c]
symbol = ""
style = 'fg:c'
text = 'fg:languages'
format = '[ $symbol]($style)[ $version ]($text)'

[cmd_duration]
min_time = 1000
style = 'fg:duration'
format = '[[ $duration]($style)]($style)'

#[docker_context]
#symbol = " "
#format = '[[ $symbol $context ](bg:#06969A)]($style) $path'

[elixir]
symbol = ""
style = 'fg:elixir'
text = 'fg:languages'
format = '[ $symbol]($style)[ $version ]($text)'

[fill]
symbol='━'

[git_branch]
symbol = ""
style = 'fg:git'
format = '[ $symbol $branch]($style)'

[git_status]
style = 'fg:git'
format = '[ $all_status$ahead_behind ]($style)'

[golang]
symbol = ""
style = 'golang'
text = 'fg:languages'
format = '[ $symbol]($style)[ $version ]($text)'

[haskell]
symbol = " "
style = 'fg:haskell'
text = 'fg:languages'
format = '[ $symbol]($style)[ $version ]($text)'

[java]
symbol = ""
style = 'fg:java'
text = 'fg:languages'
format = '[ $symbol]($style)[ $version ]($text)'

[julia]
symbol = ""
style = 'fg:julia'
text = 'fg:languages'
format = '[ $symbol]($style)[ $version ]($text)'

[nodejs]
symbol = ""
style = 'fg:nodejs'
text = 'fg:languages'
format = '[ $symbol]($style)[ $version ]($text)'

[os]
disabled = false
style = 'fg:os'
format = '[[$symbol]($style)]($style)'

[rust]
symbol = ""
style = 'fg:rust'
text = 'fg:languages'
format = '[ $symbol]($style)[ $version ]($text)'

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "
