# Startup
echo "" && pfetch


# Basic auto/tab complete:
autoload -U compinit
zstyle ':completion:*' menu select
zmodload zsh/complist
compinit

# Aliases
alias Projects='cd ~/Documents/Projects/'
alias Downloads="cd ~/Downloads"
alias Documents="cd ~/Documents"
#alias apts="sudo apt update; sudo apt upgrade"
alias brews="brew update; brew upgrade; brew autoremove; brew doctor"
alias cargos="cargo install-update -a"
alias buildvi="cd ~/Documents/Projects/dotfiles/source/neovim && git pull && make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install && cd ~"
alias ds_store="sudo find /* -name ".DS_Store" -delete"
# Getting rusty
alias grep='rg'
alias cat='bat'


# NEOVIM
alias vi="nvim"
alias vim="nvim"
export EDITOR='nvim'
export VISUAL='nvim'

# Custom paths
export CARGO_HOME="$HOME/.config/cargo"
export RUSTUP_HOME="$HOME/.cargo/rustup"
export STARSHIP_CONFIG="$HOME/.config/starship/starship.toml"

# History stuff
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Starship prompt
eval "$(starship init zsh)"

# Downloaded packages
source ~/.config/zsh/catppuccin_mocha-zsh-syntax-highlighting.zsh
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/zsh/zsh-history-substring-search/zsh-history-substring-search.zsh
